theme: jekyll-theme-cayman
title: [Precision Angle Seeking in Robots: A Reinforcement Learning Approach in Simulation and Reality]
description: [A Reinforcement Learning Approach for Real-World and Simulated Environments with Open Source Implementations.]
